### PR TITLE
Standardize file names

### LINKED ISSUE #19: Error after clean install
Hi, I just installed this package using the following command :

> sebastien@computer:~$ wp package install git@github.com:wp-cli/i18n-command.git
> Installing package wp-cli/i18n-command (dev-master)
> Updating /home/sebastien/.wp-cli/packages/composer.json to require the package...
> Registering git@github.com:wp-cli/i18n-command.git as a VCS repository...
> Using Composer to install the package...
> \---
> Loading composer repositories with package information
> Updating dependencies
> Resolving dependencies through SAT
> Dependency resolution completed in 0.630 seconds
> Analyzed 5408 packages to resolve dependencies
> Analyzed 311465 rules to resolve dependencies
> Package operations: 3 installs, 0 updates, 0 removals
> Installs: gettext/languages:2.3.0, gettext/gettext:v4.4.3, wp-cli/i18n-command:dev-master 93c1109
>  - Installing gettext/languages (2.3.0)
>  - Warning: gettext/gettext v4.4.3 requires gettext/languages ^2.3 -> satisfiable by gettext/languages[2.3.0].
>  - Installing gettext/gettext (v4.4.3)
>  - Warning: wp-cli/i18n-command dev-master requires gettext/gettext ^4.4 -> satisfiable by gettext/gettext[v4.4.0, v4.4.1, v4.4.2, v4.4.3].
>  - Installing wp-cli/i18n-command (dev-master 93c1109)
> Writing lock file
> Generating autoload files
> \---
> Success: Package installed.

---

But when I want to use it, I got this error message :

> sebastien@computer:~$ wp i18n
> Error: Callable "\\WP_CLI\\I18n\\Command_Namespace" does not exist, and cannot be registered as `wp i18n`.

---

Here the tree of my `.wp-cli` folder :

> sebastien@computer:~$ find .wp-cli -type d
> .wp-cli
> .wp-cli/packages
> .wp-cli/packages/vendor
> .wp-cli/packages/vendor/bin
> .wp-cli/packages/vendor/wp-cli
> .wp-cli/packages/vendor/wp-cli/i18n-command
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/info
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/logs
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/logs/refs
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/logs/refs/heads
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/logs/refs/remotes
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/logs/refs/remotes/origin
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/logs/refs/remotes/composer
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/branches
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/refs
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/refs/tags
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/refs/heads
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/refs/remotes
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/refs/remotes/origin
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/refs/remotes/composer
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/objects
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/objects/pack
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/objects/info
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/hooks
> .wp-cli/packages/vendor/wp-cli/i18n-command/features
> .wp-cli/packages/vendor/wp-cli/i18n-command/features/steps
> .wp-cli/packages/vendor/wp-cli/i18n-command/features/extra
> .wp-cli/packages/vendor/wp-cli/i18n-command/features/bootstrap
> .wp-cli/packages/vendor/wp-cli/i18n-command/src
> .wp-cli/packages/vendor/wp-cli/i18n-command/bin
> .wp-cli/packages/vendor/wp-cli/i18n-command/utils
> .wp-cli/packages/vendor/wp-cli/i18n-command/.github
> .wp-cli/packages/vendor/gettext
> .wp-cli/packages/vendor/gettext/gettext
> .wp-cli/packages/vendor/gettext/gettext/.git
> .wp-cli/packages/vendor/gettext/gettext/.git/info
> .wp-cli/packages/vendor/gettext/gettext/.git/logs
> .wp-cli/packages/vendor/gettext/gettext/.git/logs/refs
> .wp-cli/packages/vendor/gettext/gettext/.git/logs/refs/heads
> .wp-cli/packages/vendor/gettext/gettext/.git/logs/refs/remotes
> .wp-cli/packages/vendor/gettext/gettext/.git/logs/refs/remotes/origin
> .wp-cli/packages/vendor/gettext/gettext/.git/logs/refs/remotes/composer
> .wp-cli/packages/vendor/gettext/gettext/.git/branches
> .wp-cli/packages/vendor/gettext/gettext/.git/refs
> .wp-cli/packages/vendor/gettext/gettext/.git/refs/tags
> .wp-cli/packages/vendor/gettext/gettext/.git/refs/heads
> .wp-cli/packages/vendor/gettext/gettext/.git/refs/remotes
> .wp-cli/packages/vendor/gettext/gettext/.git/refs/remotes/origin
> .wp-cli/packages/vendor/gettext/gettext/.git/refs/remotes/composer
> .wp-cli/packages/vendor/gettext/gettext/.git/objects
> .wp-cli/packages/vendor/gettext/gettext/.git/objects/pack
> .wp-cli/packages/vendor/gettext/gettext/.git/objects/info
> .wp-cli/packages/vendor/gettext/gettext/.git/hooks
> .wp-cli/packages/vendor/gettext/gettext/src
> .wp-cli/packages/vendor/gettext/gettext/src/Utils
> .wp-cli/packages/vendor/gettext/gettext/src/Generators
> .wp-cli/packages/vendor/gettext/gettext/src/Extractors
> .wp-cli/packages/vendor/gettext/gettext/tests
> .wp-cli/packages/vendor/gettext/gettext/tests/assets
> .wp-cli/packages/vendor/gettext/gettext/tests/assets/phpcode
> .wp-cli/packages/vendor/gettext/gettext/tests/assets/twig
> .wp-cli/packages/vendor/gettext/gettext/tests/assets/jscode
> .wp-cli/packages/vendor/gettext/gettext/tests/assets/po2
> .wp-cli/packages/vendor/gettext/gettext/tests/assets/po
> .wp-cli/packages/vendor/gettext/gettext/tests/assets/phpcode2
> .wp-cli/packages/vendor/gettext/gettext/tests/assets/blade
> .wp-cli/packages/vendor/gettext/gettext/tests/assets/po3
> .wp-cli/packages/vendor/gettext/gettext/tests/assets/jscode2
> .wp-cli/packages/vendor/gettext/gettext/tests/assets/phpcode3
> .wp-cli/packages/vendor/gettext/gettext/tests/assets/jed
> .wp-cli/packages/vendor/gettext/languages
> .wp-cli/packages/vendor/gettext/languages/.git
> .wp-cli/packages/vendor/gettext/languages/.git/info
> .wp-cli/packages/vendor/gettext/languages/.git/logs
> .wp-cli/packages/vendor/gettext/languages/.git/logs/refs
> .wp-cli/packages/vendor/gettext/languages/.git/logs/refs/heads
> .wp-cli/packages/vendor/gettext/languages/.git/logs/refs/remotes
> .wp-cli/packages/vendor/gettext/languages/.git/logs/refs/remotes/origin
> .wp-cli/packages/vendor/gettext/languages/.git/logs/refs/remotes/composer
> .wp-cli/packages/vendor/gettext/languages/.git/branches
> .wp-cli/packages/vendor/gettext/languages/.git/refs
> .wp-cli/packages/vendor/gettext/languages/.git/refs/tags
> .wp-cli/packages/vendor/gettext/languages/.git/refs/heads
> .wp-cli/packages/vendor/gettext/languages/.git/refs/remotes
> .wp-cli/packages/vendor/gettext/languages/.git/refs/remotes/origin
> .wp-cli/packages/vendor/gettext/languages/.git/refs/remotes/composer
> .wp-cli/packages/vendor/gettext/languages/.git/objects
> .wp-cli/packages/vendor/gettext/languages/.git/objects/pack
> .wp-cli/packages/vendor/gettext/languages/.git/objects/info
> .wp-cli/packages/vendor/gettext/languages/.git/hooks
> .wp-cli/packages/vendor/gettext/languages/src
> .wp-cli/packages/vendor/gettext/languages/src/cldr-data
> .wp-cli/packages/vendor/gettext/languages/src/cldr-data/main
> .wp-cli/packages/vendor/gettext/languages/src/cldr-data/main/en-US
> .wp-cli/packages/vendor/gettext/languages/src/cldr-data/supplemental
> .wp-cli/packages/vendor/gettext/languages/src/Exporter
> .wp-cli/packages/vendor/gettext/languages/bin
> .wp-cli/packages/vendor/gettext/languages/tests
> .wp-cli/packages/vendor/gettext/languages/tests/Get
> .wp-cli/packages/vendor/gettext/languages/tests/Rules
> .wp-cli/packages/vendor/composer

### PR DESCRIPTION
**Pull request by swissspidy**
Fixes #19.

### CODE REVIEW

File: src/CommandNamespace.php [hunk 1]
```diff
@@ -13,5 +11,5 @@
  *     $ wp i18n make-pot . languages/my-plugin.pot
  *
  */
-class Command_Namespace extends CommandNamespace {
+class CommandNamespace extends WP_CLI\Dispatcher\CommandNamespace {
```
Comment (schlessera) [inline src/CommandNamespace.php]: This breaks, as you're using a relative namespace here. So you're extending `WP_CLI\I18n\WP_CLI\Dispatcher\CommandNamespace`.

As you need to deal with two similar class names, I'd use an alias here.

So, something like this:
```
use WP_CLI\Dispatcher\CommandNamespace as BaseCommandNamespace;

class CommandNamespace extends BaseCommandNamespace {
```
