### PR TITLE
Prefix JSON files with text domain if needed

### LINKED ISSUE #197: make-json: generated file missing theme textdomain prefix
## Bug Report

I'll keep it brief – might hopefully save someones time. ;)

**Translations folder** in a theme – just as expected by `load_theme_textdomain()`:
```
languages/
    theme-slug.pot
    de_DE.po
    de_DE.mo
```

**CLI Command**
```
wp i18n make-json languages/*.po --no-purge
```

**The result**
```
languages/
    theme-slug.pot
    de_DE.po
    de_DE.mo
    languages/de_DE-a0623ef93657e56554c5ddda522ed690.json
```

The translation will not load.  
`wp_set_script_translations()` expects the file to live in `{textdomain}-{locale}-{md5}.json`.  
After renaming it accordingly the translation loads.

### PR DESCRIPTION
**Pull request by swissspidy**
Fixes #197

### CODE REVIEW

File: src/MakeJsonCommand.php [hunk 1]
```diff
@@ -132,12 +132,11 @@ public function __invoke( $args, $assoc_args ) {
 
 					if ( $update_mo_files ) {
 						$file_basename    = basename( $file->getFilename(), '.po' );
-						$destination_file = "{$destination}/{$file_basename}.mo";
+						$destination_file = "$destination/$file_basename.mo";
```
Comment (schlessera) [inline src/MakeJsonCommand.php:135]: Why remove the curly braces syntax here? That has been the syntax we're using across all repos so far...

File: src/MakeJsonCommand.php [hunk 2]
```diff
@@ -240,12 +239,18 @@ protected function make_json( $source_file, $destination, $map ) {
 
 		$base_file_name = basename( $source_file, '.po' );
 
-		foreach ( $translations as $index => $translation ) {
+		$domain = $translations->getDomain();
+
+		$base_file_name_with_domain = $domain && 0 !== strpos( $base_file_name, $domain ) ?
```
Comment (schlessera) [inline src/MakeJsonCommand.php:244]: This needs parentheses to denote the intention clearly.
```suggestion
		$base_file_name_with_domain = ( $domain && 0 !== strpos( $base_file_name, $domain ) ) ?
```

**Review by schlessera — CHANGES_REQUESTED** [review]

File: src/MakeJsonCommand.php (hunk 2 above)
Comment (swissspidy) [reply src/MakeJsonCommand.php:244]: It was an IDE recommendation to remove unneeded parentheses.

Happy to add them back, since I shouldn't have included unrelated changes here anyway.

Is there perhaps a lint rule that could enforce this kinda style?

File: src/MakeJsonCommand.php (hunk 1 above)
Comment (swissspidy) [reply src/MakeJsonCommand.php:135]: It was an IDE recommendation to remove unneeded curly braces.

Happy to add them back, since I shouldn't have included unrelated changes here anyway.

Is there perhaps a lint rule that could enforce this kinda style?

File: src/MakeJsonCommand.php (hunk 2 above)
Comment (schlessera) [reply src/MakeJsonCommand.php:244]: The parentheses are technically not needed because of the precedence rules of the different operators.

However, given this specific construct, I had a hard time reading it correctly in its raw form. I had initially thought there was a bug with an inadvertent assignment.

Comment (swissspidy) [reply src/MakeJsonCommand.php]: Rewrote it now without a ternary

File: src/MakeJsonCommand.php (hunk 1 above)
Comment (swissspidy) [reply src/MakeJsonCommand.php]: Reverted the changes now

**Review by schlessera — CHANGES_REQUESTED** [review]

**Review by schlessera — APPROVED** [review]

**Comment by drzraf** [comment]
I'm retrieving my PO files from Weblate using `wlc`: these are missing a proper `Domain` header and still, I'd expect `make-json` to be able to deal with that (eg with a `--domain` flag).
Not sure what workflow expectations are adequate, but for me, it makes sense to give control over a specific `domain` setting at the `make-json` step.

**Comment by swissspidy** [comment]
@drzraf Please open a new issue for your enhancement request instead of commenting on an old merged PR. Thanks!

I also suggest reaching out to your PO file provider to include the Domain header, as it‘s generally a good practice.
